# Generated by Django 5.0.3 on 2024-03-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo_polygon_images", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Field",
            new_name="Polygon",
        ),
        migrations.RenameField(
            model_name="polygon",
            old_name="boundary",
            new_name="coordinates",
        ),
    ]
