# Generated by Django 5.0.3 on 2024-03-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo_polygon_images", "0002_rename_field_polygon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="satelliteimage",
            old_name="field",
            new_name="polygon",
        ),
    ]
